### ISSUE TITLE
Traverse Research pull requests

### ISSUE THREAD

**Issue by Jasper-Bekkers** [Traverse-Research/opensource-ecosystem#1]
This is a list of pull requests that we have outstanding in the larger Rust and in the general opensource ecosystem.

Initial list:

- [x] [`glam-rs` Implements Vec3A directly](https://github.com/bitshifter/glam-rs/issues/102)
- [x] [`winapi-rs` Add missing SetViewInstanceMask to ID3D12GraphicsCommandList1](https://github.com/bsekura/winapi-rs/issues/1)
- [x] [`rspirv` Remove a lot of `vec!` macro invocations from Assemble ](https://github.com/gfx-rs/rspirv/issues/165)
- [x] [`rspirv` Add methods for iterating over all instructions in the module](https://github.com/gfx-rs/rspirv/issues/158)
- [x] [`rspirv` Pointer should have ty: Token<Type> instead of ty: Word](https://github.com/gfx-rs/rspirv/issues/152)
- [x] [`rspirv` OperandExceeded when using specialization constants in work group size](https://github.com/gfx-rs/rspirv/issues/151)
- [x] [`rspirv` Add OpFunctionCall explicitly](https://github.com/gfx-rs/rspirv/issues/148)
- [x] [`rust-gamedev` Improved wording in rust-gpu description](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/362)
- [x] [`rust-gamedev` Newsletter 13: A little section about rspirv-reflect](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/241)
- [ ] [`winit` 🍏 iOS threading, initial work](https://github.com/rust-windowing/winit/issues/1644)
- [x] [`dinghy` iOS environment variable support](https://github.com/sonos/dinghy/issues/120)
- [x] [`dinghy` Add arm64e support](https://github.com/sonos/dinghy/issues/119)
- [x] [`ultraviolet` Add CI](https://github.com/termhn/ultraviolet/issues/68)
- [x] [`ultraviolet` Remove `mul_add` calls in a lot of places](https://github.com/termhn/ultraviolet/issues/67)
- [x] [`SPIRV-Tools` opt: Run DCE when SPV_KHR_shader_clock is used](https://github.com/KhronosGroup/SPIRV-Tools/issues/4049)
- [x] [`ash` Update Vulkan-Headers to 1.2.162 with stable ray-tracing spec](https://github.com/MaikKlein/ash/issues/341)
- [x] [`ash` Preliminary cleanup pass](https://github.com/MaikKlein/ash/issues/339)
- [x] [`rspirv` sr: Add ray-tracing types and deduce OpPhi type in a consistent way](https://github.com/gfx-rs/rspirv/issues/175)
- [x] [`rspirv` Regenerate with final KHR Ray Tracing spec](https://github.com/gfx-rs/rspirv/issues/174)
- [x] [`rspirv` autogen: Convert from build script to runnable binary](https://github.com/gfx-rs/rspirv/issues/173)
- [x] [`DirectXShaderCompiler` Remove unnecessary trailing whitespace in files touched by #3062](https://github.com/microsoft/DirectXShaderCompiler/issues/3272)
- [ ] [`DirectXShaderCompiler` [RFC] WinAdapter: Export helper functions to interact with shimmed types](https://github.com/microsoft/DirectXShaderCompiler/issues/3265)
- [x] [`DirectXShaderCompiler` dxcisense: Allocate "TM" classes using IMalloc instead of new](https://github.com/microsoft/DirectXShaderCompiler/issues/3258)
- [x] [`DirectXShaderCompiler` Linux: Implement prefix-counted BSTR allocation in SysAllocStringLen](https://github.com/microsoft/DirectXShaderCompiler/issues/3250)
- [x] [`android-ndk-rs` ndk-build: Support NDK r22](https://github.com/rust-windowing/android-ndk-rs/issues/94)
- [ ] [`winit` [RFC] event: Unwrap user event in map_nonuser_event Err()](https://github.com/rust-windowing/winit/issues/1761)
- [x] [`winapi-rs` Updated d3d12 to SDK version 20270](https://github.com/bsekura/winapi-rs/issues/2)
- [x] [`DirectXShaderCompiler` SPIR-V: Emit RayTmaxKHR builtin for RayTCurrent IOP](https://github.com/microsoft/DirectXShaderCompiler/pull/3320)
- [x] [`ash` ray_tracing_pipeline: Pass SBT regions as reference instead of slice](https://github.com/MaikKlein/ash/pull/350)
- [x] [`Vulkan-ValidationLayers` Mark querypool slots as ENDED in vkCmdWriteAccelerationStructuresPropertiesKHR](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2439)
- [x] [`ash` Use raw pointers to static-sized arrays in FFI signatures](https://github.com/MaikKlein/ash/pull/353)
- [x] [`assert_hex` Remove $crate from core macro calls](https://github.com/wcampbell0x2a/assert_hex/pull/1) 
- [x] [`ash` Update Vulkan-Headers to 1.2.166](https://github.com/MaikKlein/ash/pull/355)
- [x] [`rspirv` emit from(ignore) on duplicate enum variants for derive_more 0.99](https://github.com/gfx-rs/rspirv/pull/181)
- [x] [`rust-clippy` size_of_in_element_count: Disable lint on division by byte-size](https://github.com/rust-lang/rust-clippy/pull/6578)
- [x] [`DirectXShaderCompiler` [spirv] external: Update SPIRV-Tools with shader_clock DCE](https://github.com/microsoft/DirectXShaderCompiler/pull/3363)
- [ ] [`DirectXShaderCompiler` [Linux] WinAdapter: Remove virtual dtors from IUnknown to fix vtable ABI
](https://github.com/microsoft/DirectXShaderCompiler/pull/3793)
- [x] [`SPIRV-Headers` spirv.core.grammar: Remove duplicate OpArbitraryFloatPowNINTEL declaration](https://github.com/KhronosGroup/SPIRV-Headers/pull/231)

**Comment by Jasper-Bekkers** [comment]
- [ ] [`glam-rs` Rkyv support](https://github.com/bitshifter/glam-rs/pull/223)

**Comment by MarijnS95** [comment]
- [ ] https://github.com/KhronosGroup/SPIRV-Reflect/pull/126

**Comment by Jasper-Bekkers** [comment]
- https://github.com/getsentry/sentry-rust/pull/363

**Comment by MarijnS95** [comment]
- https://github.com/EmbarkStudios/sentry-contrib-rust/pull/10

**Comment by MarijnS95** [comment]
- https://github.com/getsentry/sentry-rust/pull/419

**Comment by MarijnS95** [comment]
- https://github.com/getsentry/sentry-rust/pull/422

**Comment by MarijnS95** [comment]
- https://github.com/durch/rust-s3/pull/248

**Comment by Jasper-Bekkers** [comment]
* https://github.com/notify-rs/notify/pull/383

**Comment by MarijnS95** [comment]
- https://github.com/durch/rust-s3/pull/250

**Comment by Jasper-Bekkers** [comment]
- https://github.com/rust-windowing/android-ndk-rs/pull/329
- https://github.com/rust-windowing/android-ndk-rs/pull/330
- https://github.com/rust-windowing/android-ndk-rs/pull/331
- https://github.com/rust-windowing/android-ndk-rs/pull/332
- https://github.com/rust-windowing/android-ndk-rs/pull/333

**Comment by MarijnS95** [comment]
- https://github.com/1Password/arboard/pull/80
- https://github.com/YaLTeR/wl-clipboard-rs/pull/28

**Comment by MarijnS95** [comment]
- https://github.com/rust-windowing/android-ndk-rs/pull/348

**Comment by MarijnS95** [comment]
https://github.com/EmbarkStudios/sentry-contrib-rust/pull/18

**Comment by MarijnS95** [comment]
- https://github.com/dvc94ch/cargo-subcommand/pull/23
- https://github.com/dvc94ch/cargo-subcommand/pull/24
- https://github.com/rust-windowing/android-ndk-rs/pull/360

**Comment by Jasper-Bekkers** [comment]
- https://github.com/PistonDevelopers/freetype-sys/pull/106

**Comment by Jasper-Bekkers** [comment]
https://github.com/dfrg/swash/pull/30

**Comment by MarijnS95** [comment]
- https://github.com/gyscos/zstd-rs/pull/176

**Comment by MarijnS95** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/pull/4818

**Comment by MarijnS95** [comment]
- https://github.com/katyo/oboe-rs/pull/51

**Comment by MarijnS95** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/pull/5272

**Comment by KYovchevski** [comment]
- https://github.com/emilk/egui/pull/3100
- https://github.com/emilk/egui/pull/3118
- https://github.com/emilk/egui/pull/3119

**Comment by EmilioLaiso** [comment]
- https://github.com/bitshifter/glam-rs/pull/416

**Comment by tosti007** [comment]
- https://github.com/rerun-io/egui_tiles/pull/12
- https://github.com/rerun-io/egui_tiles/pull/13

**Comment by Jasper-Bekkers** [comment]
https://github.com/zeux/meshoptimizer/pull/601

**Comment by oisyn** [comment]
- https://github.com/gwihlidal/meshopt-rs/pull/32

**Comment by MarijnS95** [comment]
- https://github.com/rust-windowing/winit/pull/3636
