### ISSUE TITLE
Traverse Research open issues

### ISSUE THREAD

**Issue by Jasper-Bekkers** [Traverse-Research/opensource-ecosystem#2]
This is a collection of issues we have outstanding within the Rust and general open-source ecosystem.

- [ ] [`physx-rs` Android CI and testing](https://github.com/EmbarkStudios/physx-rs/issues/68)
- [x] [`rspirv` Re-export spirv_headers from rspirv.](https://github.com/gfx-rs/rspirv/issues/144)
- [x] [`rspirv` Publish a new version of rspirv](https://github.com/gfx-rs/rspirv/issues/143)
- [ ] [`DirectXShaderCompiler` [SPIR-V]  arrays of RW/append/consume structured buffers unsupported](https://github.com/microsoft/DirectXShaderCompiler/issues/3281)
- [x] [`DirectXShaderCompiler` Remove voice from build script](https://github.com/microsoft/DirectXShaderCompiler/issues/3277)
- [x] [`DirectXShaderCompiler` [SPIRV] Inline ray tracing doesn't compile](https://github.com/microsoft/DirectXShaderCompiler/issues/3047)
- [x] [`DirectXShaderCompiler` [SPIRV] Invalid shader crashes compiler](https://github.com/microsoft/DirectXShaderCompiler/issues/3045)
- [x] [`DirectXShaderCompiler` [SPIR-V] The result pointer storage class and base pointer storage class in OpAccessChain do not match](https://github.com/microsoft/DirectXShaderCompiler/issues/3035)
- [x] [`DirectXShaderCompiler` [SPIR-V] Ray tracing incorrectly requires Vulkan 1.2](https://github.com/microsoft/DirectXShaderCompiler/issues/2984)
- [x] [`android-ndk-rs` Please post a new release](https://github.com/rust-windowing/android-ndk-rs/issues/44)
- [ ] [`bytes` BytesMut::freeze is not zero-cost](https://github.com/tokio-rs/bytes/issues/401)
- [ ] [`DirectXShaderCompiler` [SPIR-V] Not passing scope to vk::ReadClock results in ICE](https://github.com/microsoft/DirectXShaderCompiler/issues/3299)
- [x] [`DirectXShaderCompiler` [SPIR-V] Atomic counter emitted when combining RWStructuredBuffer and RayQuery](https://github.com/microsoft/DirectXShaderCompiler/issues/3287)
- [x] [`DirectXShaderCompiler` [SPIR-V] Support KHR Ray tracing's OpTerminateRayKHR and OpIgnoreIntersectionKHR](https://github.com/microsoft/DirectXShaderCompiler/issues/3285)
- [x] [`android-ndk-rs` Linking against C++ STL and using it at runtime](https://github.com/rust-windowing/android-ndk-rs/issues/19)
- [x] #3
- [ ] [`Vulkan-ValidationLayers` Crash in PrefilterBindRequestMap::FilteredMap](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2423)
- [ ] [`backtrace-rs` WaitForSingleObjectEx returns WAIT_ABANDONED when collecting backtraces
](https://github.com/rust-lang/backtrace-rs/issues/399)
- [x] [`rust-clippy` size_of_in_element_count false-positive when dividing byte-size by element size](https://github.com/rust-lang/rust-clippy/issues/6511)
- [x] https://github.com/KhronosGroup/Vulkan-Headers/issues/230

**Comment by Jasper-Bekkers** [comment]
- [ ] [`DirectXShaderCompiler` Provide public DXIL specification ](https://github.com/microsoft/DirectXShaderCompiler/issues/3360)

**Comment by Jasper-Bekkers** [comment]
- [ ] [`DirectXShaderCompiler` [spirv] Fix storage class for ptr-to-ptr in Vulkan 1.2.](https://github.com/microsoft/DirectXShaderCompiler/pull/3344) (blocked by this issue - not filed by us).

**Comment by Jasper-Bekkers** [comment]
- [ ] [`DirectXShaderCompiler` [SPIR-V] ByteAddressBuffer doesn't emit RowMaj or ColMaj decorations for templated loads ](https://github.com/microsoft/DirectXShaderCompiler/issues/3370)

**Comment by Jasper-Bekkers** [comment]
- [`DirectXShaderCompiler`  DXIL ByteAddressBuffer doesn't support float4x4 in templated load](https://github.com/microsoft/DirectXShaderCompiler/issues/3371)

**Comment by Jasper-Bekkers** [comment]
- [ ] [`DirectXShaderCompiler` [SPIR-V] Templated ByteAddressBuffer Load should get vectorized ](https://github.com/microsoft/DirectXShaderCompiler/issues/3372)

**Comment by DBouma** [comment]
- [ ] [ `DirectXShaderCompiler` DXIL Inline raytracing does not work with bindless tlases.](https://github.com/microsoft/DirectXShaderCompiler/issues/3412)

**Comment by DBouma** [comment]
- [ ] [ `DirectXShaderCompiler` DXIL Modifying recursive payload does not work](https://github.com/microsoft/DirectXShaderCompiler/issues/3414)

**Comment by Jasper-Bekkers** [comment]
- [ ] [`DirectXShaderCompiler` Rebase hlsl-2021 branch on top of master](https://github.com/microsoft/DirectXShaderCompiler/issues/3696)

**Comment by Jasper-Bekkers** [comment]
- [ ] [`spirv-cross` Bindings don't get picked up](https://github.com/KhronosGroup/SPIRV-Cross/issues/1718)

**Comment by DBouma** [comment]
- [ ] [ `Infinite loop issue.](https://github.com/microsoft/DirectXShaderCompiler/issues/3906)

**Comment by Jasper-Bekkers** [comment]
- [ ] [`DirectXShaderCompiler`
ResourceDescriptorHeap doesn't work properly with templates (hlsl-2021)](https://github.com/microsoft/DirectXShaderCompiler/issues/3731)

**Comment by Jasper-Bekkers** [comment]
- [ ] [`DirectXShaderCompiler` Template type on struct breaks this pointer (hlsl-2021) ](https://github.com/microsoft/DirectXShaderCompiler/issues/3732)

**Comment by Jasper-Bekkers** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/issues/4029

**Comment by Jasper-Bekkers** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/issues/4028

**Comment by DBouma** [comment]
-[ ] [QoL improvement for displaying GPU profiling information](https://github.com/EmbarkStudios/puffin/issues/59)

**Comment by MarijnS95** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/issues/4212

**Comment by Jasper-Bekkers** [comment]
- [ ] [`nng-rs` Multi-threading soundness bug in `Socket`](https://gitlab.com/neachdainn/nng-rs/-/issues/56)

**Comment by MarijnS95** [comment]
- https://github.com/microsoft/com-rs/issues/236

**Comment by DBouma** [comment]
- [ ] [[SPIR-V] Shader target stage is undefined](https://github.com/microsoft/DirectXShaderCompiler/issues/4294)

**Comment by DBouma** [comment]
- [ ] [Bitfield members are broken when used in combination with push constants](https://github.com/microsoft/DirectXShaderCompiler/issues/4295)

**Comment by MarijnS95** [comment]
- [] https://github.com/microsoft/DirectXShaderCompiler/issues/4358

**Comment by manon-traverse** [comment]
- [ ] https://github.com/KhronosGroup/SPIRV-Tools/issues/4796
- [ ] https://github.com/microsoft/DirectXShaderCompiler/issues/4444

**Comment by DBouma** [comment]
- [ ] https://github.com/microsoft/DirectXShaderCompiler/issues/4583

**Comment by MarijnS95** [comment]
- https://github.com/android/ndk/issues/1763
- https://github.com/android/ndk/issues/1764

**Comment by hannes-vernooij** [comment]
[ ] https://github.com/microsoft/DirectXShaderCompiler/issues/4698

**Comment by KYovchevski** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/issues/4727

**Comment by MarijnS95** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/issues/4731

**Comment by MarijnS95** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/issues/4792

**Comment by Jasper-Bekkers** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/issues/4819

**Comment by MarijnS95** [comment]
- https://github.com/EmbarkStudios/cargo-deny/issues/490

**Comment by MarijnS95** [comment]
- https://github.com/microsoft/DirectXShaderCompiler/issues/4742
- https://github.com/microsoft/DirectXShaderCompiler/issues/4792
- https://github.com/microsoft/DirectXShaderCompiler/issues/5090
- https://github.com/microsoft/DirectXShaderCompiler/issues/5093
- https://github.com/microsoft/DirectXShaderCompiler/issues/5261
- https://github.com/microsoft/DirectXShaderCompiler/issues/5271
- https://github.com/microsoft/DirectXShaderCompiler/issues/5273

**Comment by tosti007** [comment]
- https://github.com/rerun-io/egui_tiles/issues/10
- https://github.com/rerun-io/egui_tiles/issues/11

**Comment by MarijnS95** [comment]
- https://github.com/servo/rust-stb-image/issues/107
- https://github.com/nical/lyon/issues/881

**Comment by tosti007** [comment]
- https://github.com/EmbarkStudios/puffin/issues/205
